use crate::profile_function;

profile_function!(
    ip_list_rcv,
    ip_sublist_rcv,
    ip_rcv,
    ip_rcv_core,
    ip_rcv_finish,
    ip_rcv_finish_core_p_isra_p_0,
    ip_local_deliver,
    ip_mr_input,
    ip_send_skb,
    ip_route_input_rcu_p_part_p_0,
    ip_route_input_noref,
    ip_route_input_slow,
    __fib_lookup,
    fib_table_lookup,
    xdst_queue_output,
    ip_forward,
    ip_forward_options,
    ip_send_check,
    __icmp_send,
    icmp_push_reply,
    ip_append_data,
    ip_setup_cork_p_constprop_p_0,
);